
language: php

git:
  depth: 5

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - hhvm

before_script:
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-rm xdebug.ini; fi;

install:
    - composer self-update
    - composer install
 
script:
    - ./vendor/bin/phpunit
